apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/apcat/bigtable-emulator
      context: bigtable-emulator
    - image: ghcr.io/apcat/firestore-emulator
      context: firestore-emulator
    - image: ghcr.io/apcat/pubsub-emulator
      context: pubsub-emulator
