name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3.0.11
        with:
          path: ~/.skaffold/cache
          key: ${{ runner.os }}-skaffold-${{ hashFiles('skaffold.yaml') }}
          restore-keys: |
            ${{ runner.os }}-skaffold-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
      - name: Set up Skaffold
        run: |
          gcloud config set core/disable_prompts true
          gcloud config set core/disable_usage_reporting true
          gcloud config set component_manager/disable_update_check true
          gcloud components install skaffold
          skaffold version
          skaffold config set --global collect-metrics false
      - name: Set up container-structure-test
        run: |
          cd /tmp
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          recursive: true
      - name: skaffold build and test
        if: github.event_name != 'push'
        env:
          CLOUDSDK_CORE_VERBOSITY: none
        run: |
          skaffold build --file-output=tags.json
          skaffold test --build-artifacts=tags.json
      - name: skaffold build and push
        if: github.event_name == 'push'
        env:
          CLOUDSDK_CORE_VERBOSITY: none
        run: |
          skaffold build --push
          skaffold build --tag=latest --push
